[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["**/*"]

[deploy]
healthcheckPath = "/api/nodes/stats"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
